eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
    port:
        ${SERVER_PORT:9960}

spring:
    application:
        name: service-client


feign:
    httpclient:
        enabled: true
    hystrix:
        enabled: true


