eureka:
    instance:
        # preferIpAddress: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
    client:
        # healthcheck.enable: true
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# hystrix.command.default.execution.timeout.enabled: false

server:
    port: ${SERVER_PORT:9999}

spring:
    application:
        name: gateway

zuul:
    routes:
        serviceCore:
            path: /api/core/**
            serviceId: service-core

        serviceSms:
            path: /api/sms/**
            serviceId: service-sms

        serviceClient:
            path: /api/client/**
            serviceId: service-client