version: '3'
services:
  eureka-server-01:
    image: java:openjdk-8-jre-alpine
    ports:
      - "8761:8761"
    environment:
      TZ: 'Asia/Shanghai'
      EUREKA_HOSTNAME: 'eureka-server-01'
      EUREKA_URI: 'http://eureka-server-02:8762/eureka/'
      SERVER_PORT: 8761
    volumes:
      - "./eureka-server.jar:/opt/eureka-server.jar"
    command: java -jar /opt/eureka-server.jar

  eureka-server-02:
    image: java:openjdk-8-jre-alpine
    ports:
      - "8762:8762"
    environment:
      TZ: 'Asia/Shanghai'
      EUREKA_HOSTNAME: 'eureka-server-02'
      EUREKA_URI: 'http://eureka-server-01:8761/eureka/'
      SERVER_PORT: 8762
    volumes:
      - "./eureka-server.jar:/opt/eureka-server.jar"
    command: java -jar /opt/eureka-server.jar

  config-server-01:
    image: java:openjdk-8-jre-alpine
    ports:
      - "8888:8888"
    environment:
      TZ: 'Asia/Shanghai'
      EUREKA_URI: 'http://eureka-server-01:8761/eureka/,http://eureka-server-02:8762/eureka/'
      SERVER_PORT: 8888
    volumes:
      - "./config-server.jar:/opt/config-server.jar"
    command: java -jar /opt/config-server.jar

  gateway-01:
    image: java:openjdk-8-jre-alpine
    ports:
      - "9999:9999"
    environment:
      TZ: 'Asia/Shanghai'
      EUREKA_URI: 'http://eureka-server-01:8761/eureka/,http://eureka-server-02:8762/eureka/'
      SERVER_PORT: 9999
    volumes:
      - "./gateway.jar:/opt/gateway.jar"
    command: java -jar /opt/gateway.jar

  service-core-01:
    image: java:openjdk-8-jre-alpine
    ports:
      - "9980:9980"
    environment:
      TZ: 'Asia/Shanghai'
      EUREKA_URI: 'http://eureka-server-01:8761/eureka/,http://eureka-server-02:8762/eureka/'
      SERVER_PORT: 9980
    volumes:
      - "./service-core.jar:/opt/service-core.jar"
    command: java -jar /opt/service-core.jar

  service-sms-01:
      image: java:openjdk-8-jre-alpine
      ports:
        - "9970:9970"
      environment:
        TZ: 'Asia/Shanghai'
        EUREKA_URI: 'http://eureka-server-01:8761/eureka/,http://eureka-server-02:8762/eureka/'
        SERVER_PORT: 9970
      volumes:
        - "./service-sms.jar:/opt/service-sms.jar"
      command: java -jar /opt/service-sms.jar

  service-client-01:
        image: java:openjdk-8-jre-alpine
        ports:
          - "9960:9960"
        environment:
          TZ: 'Asia/Shanghai'
          EUREKA_URI: 'http://eureka-server-01:8761/eureka/,http://eureka-server-02:8762/eureka/'
          SERVER_PORT: 9960
        volumes:
          - "./service-client.jar:/opt/service-client.jar"
        command: java -jar /opt/service-client.jar