server:
   port: ${SERVER_PORT:8761}
   # eviction-interval-timer-in-ms: 5

eureka:
   instance:
      hostname: ${EUREKA_HOSTNAME:localhost}

   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
    application:
        name: eureka-server