spring:
    application:
        name: service-sms

    datasource:
        platform: h2
        # schema: classpath:schema.sql
        # data: classpath:data.sql

        # type: com.alibaba.druid.pool.DruidDataSource
        # url: jdbc:mysql://localhost:3306/mytest
        # username: root
        # password: root
        # driver-class-name: com.mysql.jdbc.Driver

    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true

    rabbitmq:
            host: localhost
            port: 5672
            username: springcloud
            password: 123456

server:
    port: ${SERVER_PORT:9970}

management:
    security:
        enabled: false

