eureka:
   client:
      serviceUrl:
          defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
    application:
        name: service-sms

    cloud:
        config:
            label: master
            profile: dev
            # uri: http://localhost:8888/
            discovery:
                enabled: true
                serviceId: config-server

    rabbitmq:
            host: localhost
            port: 5672
            username: springcloud
            password: 123456

server:
    port: ${SERVER_PORT:9970}

management:
    security:
        enabled: false

