spring:
    application:
        name: service-sms

    cloud:
        config:
            label: master
            profile: dev
            # uri: http://localhost:8888/
            discovery:
                enabled: true
                serviceId: config-server

server:
    port: 8881

management:
    security:
        enabled: false

