server:
    port: ${SERVER_PORT:8887}

spring:
    cloud:
       config:
          server:
             git:
               uri: https://github.com/520github/sbc
               searchPaths: config-file

    application:
       name: config-server

    rabbitmq:
        host: localhost
        port: 5672
        username: springcloud
        password: 123456

management:
    security:
        enabled: false