eureka:
   client:
      serviceUrl:
          defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
    port: ${SERVER_PORT:8888}

spring:
    cloud:
       config:
          server:
             git:
               uri: https://github.com/520github/sbc
               searchPaths: config-file

    application:
       name: config-server

    rabbitmq:
        host: localhost
        port: 5672
        username: springcloud
        password: 123456

management:
    security:
        enabled: false